### PR TITLE
Fix cert finding logic and ensure context cleanup for windows

### PR DESCRIPTION
**Pull request by gehhilfe**
- Ensure the context are cleaned up when not returned
- Iterate all certificates for each issuer

I noticed during some testing with multiple certificates contained in a Windows store that only the first certificate is iterated instead of all.
When changing that all certs are iterated for each issuer, it also needs to free last context if is not returned to the caller.
At least, following the win32 wincrypt documentation: 

[in] pPrevCertContext

A pointer to the last [CERT_CONTEXT](https://learn.microsoft.com/en-us/windows/desktop/api/wincrypt/ns-wincrypt-cert_context) structure returned by this function. This parameter must be NULL on the first call of the function. To find successive certificates meeting the search criteria, set pPrevCertContext to the pointer returned by the previous call to the function. This function frees the CERT_CONTEXT referenced by non-NULL values of this parameter.

A non-NULL [CERT_CONTEXT](https://learn.microsoft.com/en-us/windows/desktop/api/wincrypt/ns-wincrypt-cert_context) that CertFindCertificateInStore returns must be freed by [CertFreeCertificateContext](https://learn.microsoft.com/en-us/windows/desktop/api/wincrypt/nf-wincrypt-certfreecertificatecontext) or by being passed as the pPrevCertContext parameter on a subsequent call to CertFindCertificateInStore

I marked this as draft because I want to test this more and maybe clean up the code a bit more the nested for loops are quite complex

### CODE REVIEW

**Comment by mit-da** [comment]
Thanks for the PR, will be reviewing in a bit.

**Comment by mit-da** [comment]
Give us a shout when you think its ready for review and I'll take a look.

**Comment by gehhilfe** [comment]
Ready to review. 
I removed additional free, because the loop `for cert != nil` is executed one last time after the last certificate is found for a issuer and frees the prev context.

**Review by mit-da — APPROVED** [review]
thanks, lgtm

**Pull request merged**
